//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BO22EB16.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=YOUR_SERVER_HERE,YOUR_PORT_HERE;Initial Catalog=YOUR_CATALOG_HERE;Persist " +
            "Security Info=False;User ID=YOUR_USERID_HERE;Password=YOUR_PASSWORD_HERE;Multipl" +
            "eActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Tim" +
            "eout=30;")]
        public string bo22eb16ConnectionString {
            get {
                return ((string)(this["bo22eb16ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("YOUR_EMAIL_ADDRESS_PASSWORD_FOR_VERIFICATION_HERE")]
        public string PassordEpostVerifisering {
            get {
                return ((string)(this["PassordEpostVerifisering"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("YOUR_EMAIL_ADDRESS_FOR_VERIFICATION_HERE")]
        public string EpostVerifisering {
            get {
                return ((string)(this["EpostVerifisering"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("smtp.gmail.com")]
        public string EmailTypeVerifisering {
            get {
                return ((string)(this["EmailTypeVerifisering"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("YOUR_APP_DEMO_LOGGIN_EMAIL_HERE")]
        public string GuestAccountEmail {
            get {
                return ((string)(this["GuestAccountEmail"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("YOUR_APP_DEMO_LOGGIN_PASSWORD_HERE")]
        public string GuestAccountPassword {
            get {
                return ((string)(this["GuestAccountPassword"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("YOUR_GOOGLE_CLOUD_API_KEY_HERE")]
        public string GoogleMapApiKey {
            get {
                return ((string)(this["GoogleMapApiKey"]));
            }
        }
    }
}
